# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

env:
  JVER=1.02

before_install:
  - make -f Makefile.travis before_install
install:
  - make -f Makefile.travis install
