# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty
addons:
  apt:
    packages:
    - gcc
    - libboost-dev
    - google-perftools
    - libgoogle-perftools-dev
before_install:
  - chmod +x ./install_jumanpp.sh
install:
   - ./install_jumanpp.sh
