# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty
cran: https://cran.rstudio.com/
addons:
  apt:
    packages:
    - gcc
    - build-essential
before_install:
  - chmod +x ./install_jumanpp.sh
  - sudo apt-get install r-cran-magrittr r-cran-stringr r-cran-testthat
install:
   - ./install_jumanpp.sh
