# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

matrix:
  include:
    - env: JVER=1.02
      compiler: gcc
      addons:
        apt:
          update: true
          packages:
            - libboost-all-dev
            - google-perftools
            - libgoogle-perftools-dev
            - build-essential
            - g++
            - make
            - wget

install:
  - make -f Makefile.travis install
