# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

matrix:
  include:
    - env: COMPILER=g++-6 BUILD=Debug STANDARD=14 JVER=1.02
      compiler: gcc
      addons:
        apt:
          update: true
          sources:
            - sourceline: 'ppa:mhier/libboost-latest'
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - boost1.67
            - cmake
            - cmake-data

install:
  - make -f Makefile.travis install
