install:
	# JUMAN++
	mkdir Downloads
	cd Downloads
	wget http://lotus.kuee.kyoto-u.ac.jp/nl-resource/jumanpp/jumanpp-$(JVER).tar.xz
	tar xJvf jumanpp-$(JVER).tar.xz
	cd jumanpp-$(JVER)
	mkdir bld
	cd bld
	cmake ..
	sudo make install
